services:
  - type: web
    name: ai-interview-chatbot-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-interview-chatbot-backend.onrender.com

  - type: web
    name: ai-interview-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: sqlite:///./interview_chatbot.db
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://ai-interview-chatbot-frontend.onrender.com 