services:
  - type: web
    name: ai-interview-chatbot-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: ai-interview-chatbot-backend
          type: web
          property: url

  - type: web
    name: ai-interview-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: interview-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: interview-db
    databaseName: interview_chatbot
    ipAllowList: [] 