name: ai-interview-chatbot
services:
  - name: frontend
    github:
      branch: main
      repo: your-github-username/your-repo-name
      deploy_on_push: true
    source_dir: frontend
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_size_slug: basic-xs
    envs:
      - key: VITE_API_URL
        value: ${_self.BACKEND_URL}

  - name: backend
    github:
      branch: main
      repo: your-github-username/your-repo-name
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: Dockerfile.backend
    http_port: 5000
    instance_size_slug: basic-xs
    envs:
      - key: OPENAI_API_KEY
        type: SECRET
        value: ""
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: JWT_SECRET
        type: SECRET
        value: ""

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "14"

  - engine: REDIS
    name: redis
    num_nodes: 1
    size: db-s-dev-database
    version: "6" 