app = "interview-chatbot-backend"
primary_region = "dfw"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHON_VERSION = "3.9"
  PORT = "8080"
  ENVIRONMENT = "production"
  ALLOWED_ORIGINS = "*"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 